AWSTemplateFormatVersion: 2010-09-09

Parameters:

  StackUrl:
    Type: String

  Stage:
    Type: String

#Mappings:

#Conditions:

Resources:

  #Ec2 Image Builder
  Ec2ImageBuilderSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackUrl: !Ref StackUrl
        SubnetIdList: !GetAtt ImageBuilderVpcSubStack.Outputs.PublicSubnetIdList
        VpcId: !GetAtt ImageBuilderVpcSubStack.Outputs.VpcId
      TemplateURL: !Sub ${StackUrl}/ec2-image-builder/cloudformation.yaml

  #Vpc
  ImageBuilderVpcSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZoneCount: 1
        CidrClassB: 1
        CreateNatGateways: false
        Name: foundation
        Sequence: 1
        StackUrl: !Ref StackUrl
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/vpc/cloudformation.yaml

#Outputs:
