AWSTemplateFormatVersion: 2010-09-09

Parameters:

  BuildDefaultVpc:
    AllowedValues:
      - false
      - true
    Default: true
    Type: String

  DefaultVpcAvailabilityZoneCount:
    Default: 2
    Type: String

  DefaultVpcCidrClassB:
    Default: 1
    Type: String

  DefaultVpcCreateNatGateways:
    AllowedValues:
      - false
      - true
    Default: true
    Type: String

  DefaultVpcSequence:
    Default: 1
    Type: String

  DefaltVpcNamespace:
    Default: foundation
    Type: String

  Domain:
    Default: none
    Type: String

  StackUrl:
    Type: String

  Stage:
    Type: String

#Mappings:

Conditions:

  HasDomain: !Not [ !Equals [ !Ref Domain, none ] ]
  ShouldBuildDefaultVpc: !Equals [ !Ref BuildDefaultVpc, true ]

Resources:

  #Ec2 Image Builder
  Ec2ImageBuilderSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackUrl: !Ref StackUrl
        SubnetIdList: !GetAtt ImageBuilderVpcSubStack.Outputs.PublicSubnetIdList
        VpcId: !GetAtt ImageBuilderVpcSubStack.Outputs.VpcId
      TemplateURL: !Sub ${StackUrl}/ec2-image-builder/cloudformation.yaml

  #Image Builder Vpc
  ImageBuilderVpcSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZoneCount: 1
        CidrClassB: 0
        CreatePrivateHostedZone: false
        CreateNatGateways: false
        Name: builder
        Sequence: 1
        StackUrl: !Ref StackUrl
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/vpc/cloudformation.yaml

  #DefaultVpc
  DefaultVpcSubStack:
    Condition: ShouldBuildDefaultVpc
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZoneCount: !Ref DefaultVpcAvailabilityZoneCount
        CidrClassB: !Ref DefaultVpcCidrClassB
        CreateNatGateways: !Ref DefaultVpcCreateNatGateways
        Domain: !Ref Domain
        Name: !Ref DefaltVpcNamespace
        PublicHostedZoneId: !If
          - HasDomain
          - !Ref PublicHostedZone
          - none
        Sequence: !Ref DefaultVpcSequence
        StackUrl: !Ref StackUrl
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/vpc/cloudformation.yaml

  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Condition: HasDomain
    Properties:
      HostedZoneConfig:
        Comment: !Sub ${Name}-${Stage}.Domain
      Name: !Sub ${Name}-${Stage}.Domain

#Outputs:
