AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnableVersioning:
    AllowedValues:
      - true
      - false
    Default: false
    Type: String

  KmsKeyId:
    Default: none
    Type: String

  SseAlgorithm:
    AllowedValues:
      - aws:kms
      - AES256
    Default: aws:kms
    Type: String

  Stage:
    Type: String

Conditions:

  EnableVersioning: !Equals [ !Ref EnableVersioning, true ]
  HasKmsKeyId: !Not [ !Equals [ !Ref KmsKeyId, none ] ]

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !If [ HasKmsKeyId, !Ref KmsKeyId, !Ref 'AWS::NoValue' ]
              SSEAlgorithm: !If [ HasKmsKeyId, 'aws:kms', !Ref SseAlgorithm ]
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-foundation-${Stage}-cloudformation-bucket
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:

  BucketArn:
    Export:
      Name: !Sub foundation-${AWS::Region}-cloudformation-bucket-arn
    Value: !GetAtt Bucket.Arn

  BucketName:
    Export:
      Name: !Sub foundation-${AWS::Region}-cloudformation-bucket-name
    Value: !Ref Bucket
